export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'
export const REGISTER_USER_RESET = 'REGISTER_USER_RESET'

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'
export const LOGOUT = 'LOGOUT'

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL'
export const GET_PROFILE_RESET = 'GET_PROFILE_RESET'

export const EMAIL_UPDATE_REQUEST = 'EMAIL_UPDATE_REQUEST'
export const EMAIL_UPDATE_SUCCESS = 'EMAIL_UPDATE_SUCCESS'
export const EMAIL_UPDATE_FAIL = 'EMAIL_UPDATE_FAIL'
export const EMAIL_UPDATE_RESET = 'EMAIL_UPDATE_RESET'

export const PHOTO_UPDATE_REQUEST = 'PHOTO_UPDATE_REQUEST'
export const PHOTO_UPDATE_SUCCESS = 'PHOTO_UPDATE_SUCCESS'
export const PHOTO_UPDATE_FAIL = 'PHOTO_UPDATE_FAIL'
export const PHOTO_UPDATE_RESET = 'PHOTO_UPDATE_RESET'

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL'
export const CHANGE_PASSWORD_RESET = 'CHANGE_PASSWORD_RESET'

export const DELETE_ACCOUNT_REQUEST = 'DELETE_ACCOUNT_REQUEST'
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS'
export const DELETE_ACCOUNT_FAIL = 'DELETE_ACCOUNT_FAIL'

export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL'

export const SINGLE_PRODUCT_REQUEST = 'SINGLE_PRODUCT_REQUEST'
export const SINGLE_PRODUCT_SUCCESS = 'SINGLE_PRODUCT_SUCCESS'
export const SINGLE_PRODUCT_FAIL = 'SINGLE_PRODUCT_FAIL'

export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_TO_CART = 'REMOVE_TO_CART'
export const FAIL_TO_CART = 'FAIL_TO_CART'
export const CLEAR_TO_CART = 'CLEAR_TO_CART'
export const ADD_SHIPPING_ADDRESS = 'ADD_SHIPPING_ADDRESS'
export const ADD_PAYMENT_METHOD = 'ADD_PAYMENT_METHOD'

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST'
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'
export const GET_ORDER_FAIL = 'GET_ORDER_FAIL'

export const USER_ORDER_REQUEST = 'USER_ORDER_REQUEST'
export const USER_ORDER_SUCCESS = 'USER_ORDER_SUCCESS'
export const USER_ORDER_FAIL = 'USER_ORDER_FAIL'
export const USER_ORDER_RESET = 'USER_ORDER_RESET'

export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_FAIL = 'CREATE_PRODUCT_FAIL'
export const CREATE_PRODUCT_RESET = 'CREATE_PRODUCT_RESET'

export const CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST'
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS'
export const CREATE_REVIEW_FAIL = 'CREATE_REVIEW_FAIL'

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST'
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'
export const UPDATE_USER_RESET = 'UPDATE_USER_RESET'
